version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: police_course         # PostgreSQL username
      POSTGRES_PASSWORD: PoliceCourse1234 # PostgreSQL password
      POSTGRES_DB: PoliceCourse       # PostgreSQL database name
    ports:
      - "5432:5432" # Expose port 5432 to the host
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist database data

volumes:
  pgdata:
