export enum DashboardRoutes {
  ROUTE_PROFILE = 0,
  ROUTE_TEST_KECERMATAN = 1,
  ROUTE_TEST_KECERMATAN_ADD = 2,
  ROUTE_EDIT_PROFILE = 3,
  ROUTE_EDIT_PASSWORD = 4,
  ROUTE_TEST_SYMBOL_DAHSBOARD = 5,
  ROUTE_PAYMENT = 6,
}